print("Demarrage 'launch.py'")
exec(open('/home/pi/PICONFLEX2000/client/setting.py').read())
exec(open('/home/pi/PICONFLEX2000/client/config.py').read())
exec(open('/home/pi/PICONFLEX2000/client/importation.py').read())
exec(open('/home/pi/PICONFLEX2000/client/setup.py').read())